//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBapplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatDate
    {
        public System.DateTime VisitDate { get; set; }
        public string phone_number { get; set; }
        public Nullable<System.DateTime> NextVisit { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
